/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class ControlData : LCM.LCM.LCMEncodable
    {
        public bool TeleopEnabled;
        public bool HaltRadio;
        public bool AutonomousEnabled;
        public bool RobotEnabled;
        public String Stage;
        public int Time;
 
        public ControlData()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xaad705cbe00f114aL;
 
        static ControlData()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.ControlData"))
                return 0L;
 
            classes.Add("forseti2.ControlData");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.TeleopEnabled); 
 
            outs.Write(this.HaltRadio); 
 
            outs.Write(this.AutonomousEnabled); 
 
            outs.Write(this.RobotEnabled); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.Stage); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.Time); 
 
        }
 
        public ControlData(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ControlData(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.ControlData _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.ControlData o = new forseti2.ControlData();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.TeleopEnabled = ins.ReadBoolean();
 
            this.HaltRadio = ins.ReadBoolean();
 
            this.AutonomousEnabled = ins.ReadBoolean();
 
            this.RobotEnabled = ins.ReadBoolean();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.Stage = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.Time = ins.ReadInt32();
 
        }
 
        public forseti2.ControlData Copy()
        {
            forseti2.ControlData outobj = new forseti2.ControlData();
            outobj.TeleopEnabled = this.TeleopEnabled;
 
            outobj.HaltRadio = this.HaltRadio;
 
            outobj.AutonomousEnabled = this.AutonomousEnabled;
 
            outobj.RobotEnabled = this.RobotEnabled;
 
            outobj.Stage = this.Stage;
 
            outobj.Time = this.Time;
 
            return outobj;
        }
    }
}

