"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class header(object):
    __slots__ = ["seq", "time"]

    def __init__(self):
        self.seq = 0
        self.time = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(header._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">id", self.seq, self.time))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != header._get_packed_fingerprint():
            raise ValueError("Decode error")
        return header._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = header()
        self.seq, self.time = struct.unpack(">id", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if header in parents: return 0
        tmphash = (0xa4eee1da213128d1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if header._packed_fingerprint is None:
            header._packed_fingerprint = struct.pack(">Q", header._get_hash_recursive([]))
        return header._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

