/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class health : LCM.LCM.LCMEncodable
    {
        public forseti2.header header;
        public double uptime;
 
        public health()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x1a3dfbebd18a044eL;
 
        static health()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.health"))
                return 0L;
 
            classes.Add("forseti2.health");
            ulong hash = LCM_FINGERPRINT_BASE
                 + forseti2.header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.uptime); 
 
        }
 
        public health(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public health(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.health _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.health o = new forseti2.health();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = forseti2.header._decodeRecursiveFactory(ins);
 
            this.uptime = ins.ReadDouble();
 
        }
 
        public forseti2.health Copy()
        {
            forseti2.health outobj = new forseti2.health();
            outobj.header = this.header.Copy();
 
            outobj.uptime = this.uptime;
 
            return outobj;
        }
    }
}

