/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class Match : LCM.LCM.LCMEncodable
    {
        public int match_number;
        public int[] team_numbers;
        public String[] team_names;
        public String gold_items_loc;
        public String blue_items_loc;
 
        public Match()
        {
            team_numbers = new int[4];
            team_names = new String[4];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0a8744135cba8418L;
 
        static Match()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.Match"))
                return 0L;
 
            classes.Add("forseti2.Match");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.match_number); 
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.team_numbers[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.team_names[a]); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
            }
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.gold_items_loc); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.blue_items_loc); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
        }
 
        public Match(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Match(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.Match _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.Match o = new forseti2.Match();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.match_number = ins.ReadInt32();
 
            this.team_numbers = new int[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.team_numbers[a] = ins.ReadInt32();
            }
 
            this.team_names = new String[(int) 4];
            for (int a = 0; a < 4; a++) {
                __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.team_names[a] = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
            }
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.gold_items_loc = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.blue_items_loc = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
        }
 
        public forseti2.Match Copy()
        {
            forseti2.Match outobj = new forseti2.Match();
            outobj.match_number = this.match_number;
 
            outobj.team_numbers = new int[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.team_numbers[a] = this.team_numbers[a];
            }
 
            outobj.team_names = new String[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.team_names[a] = this.team_names[a];
            }
 
            outobj.gold_items_loc = this.gold_items_loc;
 
            outobj.blue_items_loc = this.blue_items_loc;
 
            return outobj;
        }
    }
}

