/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package forseti2;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class piemos_override implements lcm.lcm.LCMEncodable
{
    public forseti2.header header;
    public int team;
    public boolean override;
 
    public piemos_override()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x05ced4af13b32459L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(forseti2.piemos_override.class))
            return 0L;
 
        classes.add(forseti2.piemos_override.class);
        long hash = LCM_FINGERPRINT_BASE
             + forseti2.header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeInt(this.team); 
 
        outs.writeByte( this.override ? 1 : 0); 
 
    }
 
    public piemos_override(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public piemos_override(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static forseti2.piemos_override _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        forseti2.piemos_override o = new forseti2.piemos_override();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = forseti2.header._decodeRecursiveFactory(ins);
 
        this.team = ins.readInt();
 
        this.override = ins.readByte()!=0;
 
    }
 
    public forseti2.piemos_override copy()
    {
        forseti2.piemos_override outobj = new forseti2.piemos_override();
        outobj.header = this.header.copy();
 
        outobj.team = this.team;
 
        outobj.override = this.override;
 
        return outobj;
    }
 
}

