/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class piemos_bad_rfid : LCM.LCM.LCMEncodable
    {
        public forseti2.header header;
        public int station;
 
        public piemos_bad_rfid()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0e1342d8653fd742L;
 
        static piemos_bad_rfid()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.piemos_bad_rfid"))
                return 0L;
 
            classes.Add("forseti2.piemos_bad_rfid");
            ulong hash = LCM_FINGERPRINT_BASE
                 + forseti2.header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.station); 
 
        }
 
        public piemos_bad_rfid(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public piemos_bad_rfid(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.piemos_bad_rfid _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.piemos_bad_rfid o = new forseti2.piemos_bad_rfid();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = forseti2.header._decodeRecursiveFactory(ins);
 
            this.station = ins.ReadInt32();
 
        }
 
        public forseti2.piemos_bad_rfid Copy()
        {
            forseti2.piemos_bad_rfid outobj = new forseti2.piemos_bad_rfid();
            outobj.header = this.header.Copy();
 
            outobj.station = this.station;
 
            return outobj;
        }
    }
}

