/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package forseti2;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class piemos_cmd implements lcm.lcm.LCMEncodable
{
    public forseti2.header header;
    public boolean auton;
    public boolean enabled;
    public boolean is_blue;
    public int game_time;
 
    public piemos_cmd()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa6ee79d563b22a14L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(forseti2.piemos_cmd.class))
            return 0L;
 
        classes.add(forseti2.piemos_cmd.class);
        long hash = LCM_FINGERPRINT_BASE
             + forseti2.header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeByte( this.auton ? 1 : 0); 
 
        outs.writeByte( this.enabled ? 1 : 0); 
 
        outs.writeByte( this.is_blue ? 1 : 0); 
 
        outs.writeInt(this.game_time); 
 
    }
 
    public piemos_cmd(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public piemos_cmd(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static forseti2.piemos_cmd _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        forseti2.piemos_cmd o = new forseti2.piemos_cmd();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = forseti2.header._decodeRecursiveFactory(ins);
 
        this.auton = ins.readByte()!=0;
 
        this.enabled = ins.readByte()!=0;
 
        this.is_blue = ins.readByte()!=0;
 
        this.game_time = ins.readInt();
 
    }
 
    public forseti2.piemos_cmd copy()
    {
        forseti2.piemos_cmd outobj = new forseti2.piemos_cmd();
        outobj.header = this.header.copy();
 
        outobj.auton = this.auton;
 
        outobj.enabled = this.enabled;
 
        outobj.is_blue = this.is_blue;
 
        outobj.game_time = this.game_time;
 
        return outobj;
    }
 
}

