/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class piemos_field_cmd : LCM.LCM.LCMEncodable
    {
        public forseti2.header header;
        public bool isFlash;
        public bool isStart;
        public bool isLeft;
        public long rfid_uid;
 
        public piemos_field_cmd()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x41930ef51bb056baL;
 
        static piemos_field_cmd()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.piemos_field_cmd"))
                return 0L;
 
            classes.Add("forseti2.piemos_field_cmd");
            ulong hash = LCM_FINGERPRINT_BASE
                 + forseti2.header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.isFlash); 
 
            outs.Write(this.isStart); 
 
            outs.Write(this.isLeft); 
 
            outs.Write(this.rfid_uid); 
 
        }
 
        public piemos_field_cmd(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public piemos_field_cmd(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.piemos_field_cmd _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.piemos_field_cmd o = new forseti2.piemos_field_cmd();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = forseti2.header._decodeRecursiveFactory(ins);
 
            this.isFlash = ins.ReadBoolean();
 
            this.isStart = ins.ReadBoolean();
 
            this.isLeft = ins.ReadBoolean();
 
            this.rfid_uid = ins.ReadInt64();
 
        }
 
        public forseti2.piemos_field_cmd Copy()
        {
            forseti2.piemos_field_cmd outobj = new forseti2.piemos_field_cmd();
            outobj.header = this.header.Copy();
 
            outobj.isFlash = this.isFlash;
 
            outobj.isStart = this.isStart;
 
            outobj.isLeft = this.isLeft;
 
            outobj.rfid_uid = this.rfid_uid;
 
            return outobj;
        }
    }
}

