"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class ScheduleLoadCommand(object):
    __slots__ = ["clear_first"]

    def __init__(self):
        self.clear_first = False

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(ScheduleLoadCommand._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.clear_first))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != ScheduleLoadCommand._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ScheduleLoadCommand._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ScheduleLoadCommand()
        self.clear_first = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ScheduleLoadCommand in parents: return 0
        tmphash = (0xaaa8e36c0d0612da) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ScheduleLoadCommand._packed_fingerprint is None:
            ScheduleLoadCommand._packed_fingerprint = struct.pack(">Q", ScheduleLoadCommand._get_hash_recursive([]))
        return ScheduleLoadCommand._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

