/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package forseti2;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Schedule implements lcm.lcm.LCMEncodable
{
    public int num_matches;
    public forseti2.Match matches[];
 
    public Schedule()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x90ee9e2bdd9ac3ecL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(forseti2.Schedule.class))
            return 0L;
 
        classes.add(forseti2.Schedule.class);
        long hash = LCM_FINGERPRINT_BASE
             + forseti2.Match._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_matches); 
 
        for (int a = 0; a < this.num_matches; a++) {
            this.matches[a]._encodeRecursive(outs); 
        }
 
    }
 
    public Schedule(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Schedule(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static forseti2.Schedule _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        forseti2.Schedule o = new forseti2.Schedule();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_matches = ins.readInt();
 
        this.matches = new forseti2.Match[(int) num_matches];
        for (int a = 0; a < this.num_matches; a++) {
            this.matches[a] = forseti2.Match._decodeRecursiveFactory(ins);
        }
 
    }
 
    public forseti2.Schedule copy()
    {
        forseti2.Schedule outobj = new forseti2.Schedule();
        outobj.num_matches = this.num_matches;
 
        outobj.matches = new forseti2.Match[(int) num_matches];
        for (int a = 0; a < this.num_matches; a++) {
            outobj.matches[a] = this.matches[a].copy();
        }
 
        return outobj;
    }
 
}

