/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class ScheduleLoadCommand : LCM.LCM.LCMEncodable
    {
        public bool clear_first;
 
        public ScheduleLoadCommand()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xaaa8e36c0d0612daL;
 
        static ScheduleLoadCommand()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.ScheduleLoadCommand"))
                return 0L;
 
            classes.Add("forseti2.ScheduleLoadCommand");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.clear_first); 
 
        }
 
        public ScheduleLoadCommand(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ScheduleLoadCommand(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.ScheduleLoadCommand _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.ScheduleLoadCommand o = new forseti2.ScheduleLoadCommand();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.clear_first = ins.ReadBoolean();
 
        }
 
        public forseti2.ScheduleLoadCommand Copy()
        {
            forseti2.ScheduleLoadCommand outobj = new forseti2.ScheduleLoadCommand();
            outobj.clear_first = this.clear_first;
 
            return outobj;
        }
    }
}

