/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package forseti2;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ScheduleLoadCommand implements lcm.lcm.LCMEncodable
{
    public boolean clear_first;
 
    public ScheduleLoadCommand()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xaaa8e36c0d0612daL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(forseti2.ScheduleLoadCommand.class))
            return 0L;
 
        classes.add(forseti2.ScheduleLoadCommand.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.clear_first ? 1 : 0); 
 
    }
 
    public ScheduleLoadCommand(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ScheduleLoadCommand(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static forseti2.ScheduleLoadCommand _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        forseti2.ScheduleLoadCommand o = new forseti2.ScheduleLoadCommand();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.clear_first = ins.readByte()!=0;
 
    }
 
    public forseti2.ScheduleLoadCommand copy()
    {
        forseti2.ScheduleLoadCommand outobj = new forseti2.ScheduleLoadCommand();
        outobj.clear_first = this.clear_first;
 
        return outobj;
    }
 
}

