"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import header

class score_delta(object):
    __slots__ = ["header", "blue_normal_points", "gold_normal_points", "blue_autonomous_points", "gold_autonomous_points", "blue_permanent_points", "gold_permanent_points", "blue_penalty", "gold_penalty", "bonus_possession", "bonus_points", "action_reset"]

    UNCHANGED = 0
    BLUE = 1
    GOLD = 2
    TOGGLE = 3
    NEUTRAL = 4

    def __init__(self):
        self.header = None
        self.blue_normal_points = 0
        self.gold_normal_points = 0
        self.blue_autonomous_points = 0
        self.gold_autonomous_points = 0
        self.blue_permanent_points = 0
        self.gold_permanent_points = 0
        self.blue_penalty = 0
        self.gold_penalty = 0
        self.bonus_possession = 0
        self.bonus_points = 0
        self.action_reset = False

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(score_delta._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == header.header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">bbbbbbbbbbb", self.blue_normal_points, self.gold_normal_points, self.blue_autonomous_points, self.gold_autonomous_points, self.blue_permanent_points, self.gold_permanent_points, self.blue_penalty, self.gold_penalty, self.bonus_possession, self.bonus_points, self.action_reset))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != score_delta._get_packed_fingerprint():
            raise ValueError("Decode error")
        return score_delta._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = score_delta()
        self.header = header.header._decode_one(buf)
        self.blue_normal_points, self.gold_normal_points, self.blue_autonomous_points, self.gold_autonomous_points, self.blue_permanent_points, self.gold_permanent_points, self.blue_penalty, self.gold_penalty, self.bonus_possession, self.bonus_points, self.action_reset = struct.unpack(">bbbbbbbbbbb", buf.read(11))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if score_delta in parents: return 0
        newparents = parents + [score_delta]
        tmphash = (0x81cf51dd3e6a066b+ header.header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if score_delta._packed_fingerprint is None:
            score_delta._packed_fingerprint = struct.pack(">Q", score_delta._get_hash_recursive([]))
        return score_delta._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

