"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class Time(object):
    __slots__ = ["game_time_so_far", "stage_time_so_far", "total_stage_time", "stage_name"]

    def __init__(self):
        self.game_time_so_far = 0
        self.stage_time_so_far = 0
        self.total_stage_time = 0
        self.stage_name = ""

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(Time._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iii", self.game_time_so_far, self.stage_time_so_far, self.total_stage_time))
        __stage_name_encoded = self.stage_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__stage_name_encoded)+1))
        buf.write(__stage_name_encoded)
        buf.write("\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != Time._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Time._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Time()
        self.game_time_so_far, self.stage_time_so_far, self.total_stage_time = struct.unpack(">iii", buf.read(12))
        __stage_name_len = struct.unpack('>I', buf.read(4))[0]
        self.stage_name = buf.read(__stage_name_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Time in parents: return 0
        tmphash = (0x635b8c3e2e12db04) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Time._packed_fingerprint is None:
            Time._packed_fingerprint = struct.pack(">Q", Time._get_hash_recursive([]))
        return Time._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

