"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class TimeControl(object):
    __slots__ = ["command_name"]

    def __init__(self):
        self.command_name = ""

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(TimeControl._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __command_name_encoded = self.command_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__command_name_encoded)+1))
        buf.write(__command_name_encoded)
        buf.write("\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != TimeControl._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimeControl._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = TimeControl()
        __command_name_len = struct.unpack('>I', buf.read(4))[0]
        self.command_name = buf.read(__command_name_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if TimeControl in parents: return 0
        tmphash = (0x8f3d1d62d3eef7ef) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if TimeControl._packed_fingerprint is None:
            TimeControl._packed_fingerprint = struct.pack(">Q", TimeControl._get_hash_recursive([]))
        return TimeControl._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

