/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace forseti2
{
    public sealed class Time : LCM.LCM.LCMEncodable
    {
        public int game_time_so_far;
        public int stage_time_so_far;
        public int total_stage_time;
        public String stage_name;
 
        public Time()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x635b8c3e2e12db04L;
 
        static Time()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("forseti2.Time"))
                return 0L;
 
            classes.Add("forseti2.Time");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.game_time_so_far); 
 
            outs.Write(this.stage_time_so_far); 
 
            outs.Write(this.total_stage_time); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.stage_name); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
        }
 
        public Time(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Time(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static forseti2.Time _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            forseti2.Time o = new forseti2.Time();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.game_time_so_far = ins.ReadInt32();
 
            this.stage_time_so_far = ins.ReadInt32();
 
            this.total_stage_time = ins.ReadInt32();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.stage_name = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
        }
 
        public forseti2.Time Copy()
        {
            forseti2.Time outobj = new forseti2.Time();
            outobj.game_time_so_far = this.game_time_so_far;
 
            outobj.stage_time_so_far = this.stage_time_so_far;
 
            outobj.total_stage_time = this.total_stage_time;
 
            outobj.stage_name = this.stage_name;
 
            return outobj;
        }
    }
}

