/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package fearing;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class carrier_state implements lcm.lcm.LCMEncodable
{
    public fearing.header header;
    public float battery_voltage;
 
    public carrier_state()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb3491fdcb8711763L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(fearing.carrier_state.class))
            return 0L;
 
        classes.add(fearing.carrier_state.class);
        long hash = LCM_FINGERPRINT_BASE
             + fearing.header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeFloat(this.battery_voltage); 
 
    }
 
    public carrier_state(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public carrier_state(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static fearing.carrier_state _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        fearing.carrier_state o = new fearing.carrier_state();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = fearing.header._decodeRecursiveFactory(ins);
 
        this.battery_voltage = ins.readFloat();
 
    }
 
    public fearing.carrier_state copy()
    {
        fearing.carrier_state outobj = new fearing.carrier_state();
        outobj.header = this.header.copy();
 
        outobj.battery_voltage = this.battery_voltage;
 
        return outobj;
    }
 
}

