"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import header

class carrier_state(object):
    __slots__ = ["header", "battery_voltage"]

    def __init__(self):
        self.header = None
        self.battery_voltage = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(carrier_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == header.header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">f", self.battery_voltage))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != carrier_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return carrier_state._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = carrier_state()
        self.header = header.header._decode_one(buf)
        self.battery_voltage = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if carrier_state in parents: return 0
        newparents = parents + [carrier_state]
        tmphash = (0xb3491fdcb8711763+ header.header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if carrier_state._packed_fingerprint is None:
            carrier_state._packed_fingerprint = struct.pack(">Q", carrier_state._get_hash_recursive([]))
        return carrier_state._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

